// WTF:: I know I should give up

export const layout = (addClerk: boolean, addHeroUi: boolean) => {
  const CLERK_IMPORT = addClerk
    ? `import { ClerkProvider } from "@clerk/nextjs";`
    : ``;

  const CLERK_PROVIDER_START = addClerk ? `<ClerkProvider>` : ``;
  const CLERK_PROVIDER_END = addClerk ? `</ClerkProvider>` : ``;

  const HEROUI_IMPORT = addHeroUi
    ? `import { Providers } from "@/componets/provider";`
    : ``;

  const HEROUI_START = addHeroUi
    ? `<Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>`
    : ``;
  const HEROUI_END = addHeroUi ? `</Providers>` : ``;

  return `
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
${CLERK_IMPORT}
${HEROUI_IMPORT}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    ${CLERK_PROVIDER_START}
      <html lang="en" suppressHydrationWarning>
        <body
          className={\`\${geistSans.variable} \${geistMono.variable} antialiased\`}
        >
          ${HEROUI_START}
            {children}
          ${HEROUI_END}
        </body>
      </html>
    ${CLERK_PROVIDER_END}
  );
}
`;
};
